[package]
name = "pagebrowse_types"
version = "0.1.0"
edition = "2021"
description = "Common types required for Pagebrowse communication"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
